@startuml

actor User

User -> [API Gateway]: Product Details Page
[API Gateway] --> [Price] : Price information
[API Gateway] --> [Product] :" Product Details"
[API Gateway] --> [Inventory]: " In-stock availability"
@enduml